name: Main

on:
  push:
    branches: [ develop, master ]
    tags: one.irradia.fieldrush-[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        env:
          MAVEN_CENTRAL_USERNAME:           ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD:           ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_CENTRAL_STAGING_PROFILE_ID: 'a56bb91d0cd124'
          MAVEN_CENTRAL_SIGNING_KEY_ID:     '0xEF0A1D695366A5B5'
          IRRADIA_GITHUB_ACCESS_TOKEN:      ${{ secrets.IRRADIA_GITHUB_ACCESS_TOKEN }}
        run: .ci/ci-main.sh normal
      - name: Upload test report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: junit-test-report
          path: ./one.irradia.fieldrush.tests/build/reports/tests/testDebugUnitTest/
